# Generated by Django 4.1.3 on 2022-12-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_cus_addr_alter_customer_cus_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='au_star',
        ),
        migrations.RemoveField(
            model_name='product',
            name='book_star',
        ),
    ]
