# Generated by Django 4.1.3 on 2022-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_author_au_star_remove_product_book_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
